import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950 text-neutral-100`}
      >
        <div className="sticky top-0 z-50 border-b border-white/10 bg-black/60 backdrop-blur">
          <div className="mx-auto max-w-5xl px-4 py-3 flex items-center gap-3">
            <Link className="font-semibold tracking-tight" href="/">yt-ai</Link>
            <form action="/v" className="flex-1 flex gap-2">
              <input
                type="url"
                name="url"
                placeholder="Paste any YouTube URL..."
                className="w-full rounded-md bg-neutral-900 border border-white/10 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-white/20"
              />
              <button className="rounded-md bg-white text-black px-3 py-2 text-sm font-medium hover:bg-white/90">Go</button>
            </form>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
